/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        carbon:       '#0a0a0a',
        'carbon-2':   '#131313',
        'carbon-3':   '#1d1d1d',
        paper:        '#f2ece0',
        'paper-2':    '#e8e1d2',
        'paper-3':    '#d8d0bf',
        ink:          '#0a0a0a',
        'ink-2':      '#4a4438',
        'ink-3':      '#8a8172',
        racing:       '#e10600',
        'racing-hot': '#ff2010',
        'racing-deep':'#b30400',
        gold:         '#d4a017',
        'rule-light': '#d4cec4',
        // Team colors
        mercedes:     '#27F4D2',
        ferrari:      '#E8002D',
        mclaren:      '#FF8000',
        redbull:      '#3671C6',
        williams:     '#64C4FF',
        haas:         '#B6BABD',
        alpine:       '#0093CC',
        audi:         '#00877C',
        racingbulls:  '#6692FF',
        aston:        '#229971',
        cadillac:     '#8A9099',
      },
      fontFamily: {
        playfair: ['"Playfair Display"', 'serif'],
        inter:    ['Inter', 'sans-serif'],
        mono:     ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        '9px':  ['9px', { lineHeight: '1.4' }],
        '10px': ['10px', { lineHeight: '1.4' }],
        '11px': ['11px', { lineHeight: '1.4' }],
        '13px': ['13px', { lineHeight: '1.4' }],
        '15px': ['15px', { lineHeight: '1.4' }],
        '17px': ['17px', { lineHeight: '1.4' }],
        '20px': ['20px', { lineHeight: '1' }],
        '24px': ['24px', { lineHeight: '1' }],
        '28px': ['28px', { lineHeight: '1.15' }],
        '32px': ['32px', { lineHeight: '1' }],
        '38px': ['38px', { lineHeight: '1' }],
        '48px': ['48px', { lineHeight: '1' }],
      },
      animation: {
        'fade-slow':    'fadeSlow 0.9s ease both',
        'fade-up-slow': 'fadeUpSlow 1s ease both',
        ticker:         'ticker 48s linear infinite',
        'pulse-dot':    'pulseDot 1.8s ease infinite',
        blink:          'blink 1.6s ease infinite',
        'flag-wave':    'flagWave 3s ease-in-out infinite',
        'bar-grow':     'barGrowSlow 1.4s cubic-bezier(.3,.9,.3,1) both',
        'row-slide':    'rowSlide 0.6s cubic-bezier(.25,.9,.3,1) both',
        'num-count-up': 'numCountUp 0.8s ease both',
        'mask-reveal':  'maskRevealUp 1.1s cubic-bezier(.2,.9,.25,1) both',
        'underline-draw':'underlineDraw 1.2s cubic-bezier(.3,.9,.3,1) both',
        'checker-fade': 'checkerFadeIn 0.9s cubic-bezier(.2,.8,.2,1) both',
        'speed-line':   'speedLineSlow 5.5s ease-out infinite',
      },
    },
  },
  plugins: [],
};
